# Database
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:auth_db}?&timezone=Asia/Ho_Chi_Minh
spring.datasource.username=${DB_USERNAME:auth_user}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.cache.type=redis

jwt.secret=${JWT_SECRET:DA61EF835680CD643C259B9BB5E4794B4903A137356A75F2C2D05CD2DB9BAE7A}
jwt.expiration=86400000

bootstrap.admin.username=sysadmin
bootstrap.admin.password=${ADMIN_PASSWORD:Admin@123}
bootstrap.admin.email=sysadmin@system.local

# Server configuration
server.address=0.0.0.0
server.port=8080